### ISSUE TITLE
Upgrade for 8.2 or 8.3?

### ISSUE THREAD

**Issue by hubbyist** [junichi11/netbeans-template-settings#1]
Using this plugin and it is working. But making it directly listed under available plugins in 8.2 will be good.

**Comment by junichi11** [comment]
Okay. Probably, I'll do it later.

Thanks.

**Comment by junichi11** [comment]
Done!

- https://github.com/junichi11/netbeans-template-settings/releases/tag/v1.2.0
- http://plugins.netbeans.org/plugin/57583/template-settings4p
